repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace

  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8

  - repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
      - id: autoflake
        args:
          - --in-place
          - --remove-unused-variables
          - --remove-all-unused-imports

  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0 # or specific git tag
    hooks:
      # - id: forbid-space-in-indent
      # - id: git-check # Configure in .gitattributes
      # - id: git-dirty # Configure in .gitignore
      # - id: markdownlint # Configure in .mdlrc
      # - id: require-ascii
      # - id: script-must-have-extension
      - id: shellcheck
      # - id: shfmt
